name: stagedive
description: StageDive creates a template-based project for you
author: Mike Mitterer <office@mikemitterer.at>
homepage: https://github.com/MikeMitterer/dart-stagedive

version: 0.1.0

environment:
  sdk: '>=1.0.0 <2.0.0'

# Add the bin/stagedive.dart script to the scripts pub installs.
# Activate local repo:
#   pub global activate --source path .
#
executables:
  stagedive:

dependencies:
  browser: any

  logging: any
  logging_handlers: any
  console_log_handler: any

  validate: any

  args: any
  yaml: any

  pub_cache: "^0.0.1+2"

dev_dependencies:
  test: any