name: stagedive
description: StageDive creates a template-based project for you
author: Mike Mitterer <office@mikemitterer.at>
homepage: https://github.com/MikeMitterer/dart-stagedive

version: 0.5.1

environment:
  sdk: ">=2.0.0 <3.0.0"

# Add the bin/stagedive.dart script to the scripts pub installs.
# Activate local repo:
#   pub global activate --source path .
#
executables:
  stagedive:

dependencies:
  console_log_handler: ^1.0.0
  # path: /Volumes/Daten/DevLocal/DevDart/ConsoleLogHandler

  validate: ^1.0.0

  args: ^1.0.0
  yaml: ^2.1.0

  pub_cache: ^0.2.0

dev_dependencies:
  test: any
  grinder: any

  build_runner: any
  build_test: any
