name: console
description: Add your description for console
author: Simple Console Mike
homepage: https://github.com/Simple Console/dart-console

version: 1.0.0

environment:
  sdk: '>=1.0.0 <2.0.0'

# Add the bin/console.dart script to the scripts pub installs.
# Activate local repo:
#   pub global activate --source path .
# Decativate local repo:
#   pub global deactivate console
#
executables:
  console:

dependencies:
  browser: any

  logging: any
  logging_handlers: any
  console_log_handler: any

  validate: any

  args: any
  yaml: any

dev_dependencies:
  test: any